#!/bin/sh

CWD=$(realpath $(dirname $0))
[ "$CWD" = "." ] && CWD=$(pwd)

LOGFILE=$CWD/logs/mongodb.log
PIDFILE=$CWD/logs/mongodb.pid
MONGOPID=""

mongodb_usage() {
	echo
	echo "${YELLOW} Usage: ${WHITE}$(basename $0) ${CYAN}[ start | stop | status | help ]${RESTORE}"
	echo
}

mongodb_is_running() {
	
	MONGOPID=$(pgrep mongod || { echo "pgrep failed."; echo 0; })
	[ ! "${MONGOPID}" = "0" ] \
		&& {
			echo "PID is ${MONGOPID}"
		} \
		|| {
			echo "Not running"
			exit 1
		}

	[ ${MONGOPID} -a -f /proc/${MONGOPID}/exe 2>&1 > /dev/null ] \
		&& {
			return 1
		} \
		|| {
			return 0
		}
}

mongodb_stop() {

	if [ mongodb_is_running ]; then
		echo "${WHITE}Found pid ${GREEN}[${MONGOPID}]${WHITE} at /proc/${MONGOPID}/exe${RESTORE}"
		echo -n "${YELLOW}Shutting server down:  "
		CNT=0
		while [ -f /proc/${MONGOPID}/exe ]
		do
  		((CNT++))
  		echo -ne "\b${RED}${CNT}${RESTORE}"
			kill -INT ${pid}
  		sleep 1
  	done
		echo -e "\b${GREEN} OK ${RESTORE}"
	else
		echo "${WHITE}mongod server is${RED} NOT ${WHITE}running${RESTORE}"
	fi
}

mongodb_start() {
	if [ ! mongodb_is_running ]; then
		echo "${WHITE}mongod server is${RED} NOT ${WHITE}running${RESTORE}"
		echo -n "${YELLOW}Starting server up:  "

		/opt/mongodb/bin/mongod \
			--dbpath $CWD/data \
			--bind_ip 192.168.1.70,localhost \
			--fork \
			--pidfilepath $PIDFILE \
			--logpath  $LOGFILE

		CNT=0
		while [ ! mongodb_is_running ]
		do
	  		((CNT++))
	  		echo -ne "\b${RED}${CNT}${RESTORE}"
	  		sleep 1
	  	done
		echo -e "\b${GREEN} OK ${RESTORE}"
	else
		echo "${WHITE}Found pid ${GREEN}[${MONGOPID}]${WHITE} at /proc/${MONGOPID}/exe"
	fi
}

case "$1" in
	'start')
		mongodb_start
		;;
	'stop')
		mongodb_stop
		;;
	'status')
		mongodb_is_running
		;;
	'help')
		mongodb_usage
		;;
	*)
		[ $# -eq 0 ] \
		&& {
			mongodb_stop
		} \
		|| {
			echo -e "\n${RED} Unknown option: ${WHITE} $1 ${RESTORE}\n"
			mongodb_usage
		}
		;;
esac
